//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_III_WPF.AlgotithmComputeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlgotithmComputeService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EstimateIndicator", ReplyAction="http://tempuri.org/IService1/EstimateIndicatorResponse")]
        double EstimateIndicator(double[] dataTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EstimateIndicator", ReplyAction="http://tempuri.org/IService1/EstimateIndicatorResponse")]
        System.Threading.Tasks.Task<double> EstimateIndicatorAsync(double[] dataTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : R_III_WPF.AlgotithmComputeService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<R_III_WPF.AlgotithmComputeService.IService1>, R_III_WPF.AlgotithmComputeService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double EstimateIndicator(double[] dataTime) {
            return base.Channel.EstimateIndicator(dataTime);
        }
        
        public System.Threading.Tasks.Task<double> EstimateIndicatorAsync(double[] dataTime) {
            return base.Channel.EstimateIndicatorAsync(dataTime);
        }
    }
}
